pipeline {

    //agent none
    agent {label 'mynode2'}
    
    environment {
        PASS = credentials('registry-pass') 
    }

    stages {

        stage('Build') {
            //agent {label 'mynode2'}
            steps {
                sh '''
                    ./jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./jenkins/build/build.sh
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            //agent {label 'mynode2'}
            steps {
                sh './jenkins/test/mvn.sh mvn test'
            }

            post {
                always {
                    junit 'java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            //agent {label 'mynode2'}
            steps {
                sh './jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            //agent {label 'mynode2'}
            steps {
                sh './jenkins/deploy/deploy.sh'
            }
        }
    }
}
